kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ovc-disk-csi
  name: ovc-disk-csi-driver-attacher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovc-disk-csi-driver-attacher
  template:
    metadata:
      labels:
        app: ovc-disk-csi-driver-attacher
    spec:
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: Always
          volumeMounts:
          - name: socket-dir
            mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: ovc-plugin
          image: chrisvdg/ovc-disk-csi-driver
          imagePullPolicy: Always
          args:
            - "--config=csi-config/attacher_provisioner.yaml"
            - "--verbose"
          env:
            - name: OVC_JWT
              valueFrom:
                secretKeyRef:
                  name: ovc-disk-csi-driver-secret
                  key: client_jwt
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: csi-config
              mountPath: csi-config
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: csi-config
          configMap: 
            name: csi-config
