apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-sc
  resources:
    requests:
      storage: 8Gi
