apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovc-disk-csi-driver-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: disk.ovc.csi.gig.tech
allowVolumeExpansion: true